# Weapons of Math Destruction (Cathy O'Neil)
- math + technology magnifies the reach of ML/AI systems
- many are flawed and used in the wild unchecked - there is no human in the loop to add an element of common sense and checks and bounds
- "[Mathematical techniques] churned 24/7 through petabytes of information [...] and increasingly they focused [...] on human beings [...] predicting our trustworthiness and calculating our potential as students, workers, lovers, criminals."
- these systems were faster, but also "marketed as fair and objective"
   - the undertone here is that this was erroneous and irresponsible
   - given the current events, one could even say criminally so, perpetuating systemic racism
- how does bias get introduced?
   - developing models requires choices and interpretations to be made in selecting the variables that are important and how important they are (weights)
   - these choices are made by humans and humans are fallible, despite any best intentions
      - many models encode "prejudice, misunderstanding, and bias into the software systems that increasingly managed our lives"
- 
